# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# command example: ansible-playbook -i all.inv 05-create-flavors.yml
---
- name: install contrail
  hosts: contrail-ubuntu-vm
  gather_facts: false
  tasks:

    - name: Set necessary variables
      set_fact:
        os_auth:
          auth_url: http://10.10.7.205:35357/v3
          username: admin
          password: contrail123
          project_name: admin
          os_tenant_name: admin
          project_domain_name: default
          user_domain_name: default

    - name: Import variables from the file /vars/contrail.info into 'info' variable
      include_vars:
        file: contrail.info
        name: info

    - name: download contrail-server-manager
      get_url:
        url: http://{{ info.contrail_package[0].file_server }}/ubuntu-gui.qcow2
        dest: /root/images/ubuntu-gui.qcow2

    - name: Upload GUI Image
      os_image:
        auth: "{{ os_auth }}"
        name: gui_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-gui.qcow2
        is_public: yes

    - name: Upload Primary Image 
      os_image:
        auth: "{{ os_auth }}"
        name: webserver-primary_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-webserver-primary.img
        is_public: yes

    - name: Upload Secondary Image         
      os_image:
        auth: "{{ os_auth }}"
        name: webserver-secondary_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-webserver-secondary.img
        is_public: yes

    - name: Upload DB Image         
      os_image:
        auth: "{{ os_auth }}"
        name: db_image
        container_format: bare
        disk_format: qcow2
        filename: /root/images/ubuntu-db.img
        is_public: yes

    - name: Gather facts about previously created images
      shell: openstack --os-auth-url "http://10.10.7.205:35357/v3" --os-username admin --os-project-name admin --os-tenant-name admin --os-password "contrail123" --os-default-domain-name default image list -f json
      register: image_list

    - name: Display Images
      set_fact:
        images: "{{ image_list.stdout | from_json }}"
    - debug:
        msg:
          - "{{images}}"

